PRODUCT_PACKAGES += \
    AvatarPickerPixelOverlay \
    CellBroadcastReceiverOverlay \
    CellBroadcastServiceOverlay \
    GlanceableHubConfigOverlay \
    GlanceableHubSettingsConfigOverlay2022 \
    GlanceableHubSysuiConfigOverlay \
    GoogleConfigOverlay \
    GoogleDeviceLockControllerOverlay \
    GoogleHealthConnectOverlay \
    GooglePermissionControllerOverlay \
    GoogleWebViewOverlay \
    ManagedProvisioningPixelOverlay \
    PixelAccessibilityMenu \
    PixelBuiltInPrintService \
    PixelConfigOverlay2018 \
    PixelConfigOverlay2019 \
    PixelConfigOverlay2019Midyear \
    PixelConfigOverlay2021 \
    PixelConfigOverlayCommon \
    PixelContactsProvider \
    PixelDeviceDiagnostics \
    PixelDocumentsUIGoogleOverlay \
    Pixelframework-res \
    PixelSettingsGoogle \
    PixelSettingsProvider \
    PixelSetupWizardOverlayExpressive \
    PixelSystemUIGoogle \
    PixelTelecom \
    PixelTeleService \
    PixelTetheringOverlay2021 \
    SystemUIGXOverlay \
    WildlifeSettingsVpnOverlay2022 \
