PRODUCT_PACKAGES += \
    AvatarPickerPixelOverlay \
    CellBroadcastReceiverOverlay \
    CellBroadcastServiceOverlay \
    GoogleConfigOverlay \
    GoogleDeviceLockControllerOverlay \
    GoogleHealthConnectOverlay \
    GooglePermissionControllerOverlay \
    GoogleWebViewOverlay \
    ManagedProvisioningPixelOverlay \
    PixelAccessibilityMenu \
    PixelBuiltInPrintService \
    PixelConfigOverlay2018 \
    PixelConfigOverlay2019 \
    PixelConfigOverlay2019Midyear \
    PixelConfigOverlay2021 \
    PixelConfigOverlayCommon \
    PixelConnectivityOverlay2025 \
    PixelContactsProvider \
    PixelDeviceDiagnostics \
    PixelDocumentsUIGoogleOverlay \
    Pixelframework-res \
    PixelSettingsGoogle \
    PixelSettingsProvider \
    PixelSystemUIGoogle \
    PixelTelecom \
    PixelTeleService \
    PixelTetheringOverlay2021 \
    SystemUIGXOverlay \
    WildlifeSettingsVpnOverlay2022 \
